version: '3'

services:
  dotnetspider.portal:
    image: 'dotnetspider/portal:latest'
    restart: always
    hostname: dotnetspider.portal
    container_name: dotnetspider.portal
    ports:
      - '7896:7896'
    environment:
      - ConnectionString=Database='dotnetspider';Data Source=my.com;password=1qazZAQ!;User ID=root;Port=3306;
      - KafkaBootstrapServers=my.com:9092,my.com:9093,my.com:9094
      - KafkaSaslUsername=user
      - KafkaSaslPassword=bitnami
      - KafkaSaslMechanism=Plain
      - KafkaSecurityProtocol=SaslPlaintext
      - Docker=http://my.com:2376
      - DockerVolumes=/storage/var/lib/dotnetspider/logs:/logs;/etc/hosts:/etc/hosts
      - quartz.dataSource.myDs.connectionString=Database='dotnetspider';Data Source=my.com;password=1qazZAQ!;User ID=root;Port=3306;
    volumes:
      - /storage/var/lib/dotnetspider/portal/logs:/logs