version: '3'

services:
  test-agent1:
    image: 'dotnetspider/downloader-agent:latest'
    restart: always
    hostname: test-agent1
    container_name: test-agent1
    environment:
      - KafkaBootstrapServers=my.com:9092,my.com:9093,my.com:9094
      - KafkaSaslUsername=user
      - KafkaSaslPassword=bitnami
      - KafkaSaslMechanism=Plain
      - KafkaSecurityProtocol=SaslPlaintext
      - AgentId=TEST_AGENT_001
      - AgentName=TEST_AGENT_001
    volumes:
      - /storage/var/lib/dotnetspider/test-agent1/logs:/logs
      
  test-agent2:
    image: 'dotnetspider/downloader-agent:latest'
    restart: always
    hostname: test-agent2
    container_name: test-agent2
    environment:
      - KafkaBootstrapServers=my.com:9092,my.com:9093,my.com:9094
      - KafkaSaslUsername=user
      - KafkaSaslPassword=bitnami
      - KafkaSaslMechanism=Plain
      - KafkaSecurityProtocol=SaslPlaintext
      - AgentId=TEST_AGENT_002
      - AgentName=TEST_AGENT_002
    volumes:
      - /storage/var/lib/dotnetspider/test-agent2/logs:/logs