version: '2'

services:
  kafka1:
    image: 'bitnami/kafka:latest'
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=100
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181,zoo:2182,zoo:2183
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
    volumes:
      - /storage/var/lib/kafka/data1:/bitnami/kafka
    extra_hosts:
      - zoo:192.168.1.28
  kafka2:
    image: 'bitnami/kafka:latest'
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=101
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181,zoo:2182,zoo:2183
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9093
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
    volumes:
      - /storage/var/lib/kafka/data2:/bitnami/kafka
    extra_hosts:
      - zoo:192.168.1.28

  kafka3:
    image: 'bitnami/kafka:latest'
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=102
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo:2181,zoo:2182,zoo:2183
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9094
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=bitnami
    volumes:
      - /storage/var/lib/kafka/data3:/bitnami/kafka
    extra_hosts:
      - zoo:192.168.1.28        